const followersMock = [
  {
    login: "dwillis",
    id: 2214,
    node_id: "MDQ6VXNlcjIyMTQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/2214?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dwillis",
    html_url: "https://github.com/dwillis",
    followers_url: "https://api.github.com/users/dwillis/followers",
    following_url:
      "https://api.github.com/users/dwillis/following{/other_user}",
    gists_url: "https://api.github.com/users/dwillis/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dwillis/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dwillis/subscriptions",
    organizations_url: "https://api.github.com/users/dwillis/orgs",
    repos_url: "https://api.github.com/users/dwillis/repos",
    events_url: "https://api.github.com/users/dwillis/events{/privacy}",
    received_events_url: "https://api.github.com/users/dwillis/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "zeke",
    id: 2289,
    node_id: "MDQ6VXNlcjIyODk=",
    avatar_url: "https://avatars.githubusercontent.com/u/2289?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/zeke",
    html_url: "https://github.com/zeke",
    followers_url: "https://api.github.com/users/zeke/followers",
    following_url: "https://api.github.com/users/zeke/following{/other_user}",
    gists_url: "https://api.github.com/users/zeke/gists{/gist_id}",
    starred_url: "https://api.github.com/users/zeke/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/zeke/subscriptions",
    organizations_url: "https://api.github.com/users/zeke/orgs",
    repos_url: "https://api.github.com/users/zeke/repos",
    events_url: "https://api.github.com/users/zeke/events{/privacy}",
    received_events_url: "https://api.github.com/users/zeke/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "git4rails",
    id: 6718,
    node_id: "MDQ6VXNlcjY3MTg=",
    avatar_url: "https://avatars.githubusercontent.com/u/6718?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/git4rails",
    html_url: "https://github.com/git4rails",
    followers_url: "https://api.github.com/users/git4rails/followers",
    following_url:
      "https://api.github.com/users/git4rails/following{/other_user}",
    gists_url: "https://api.github.com/users/git4rails/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/git4rails/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/git4rails/subscriptions",
    organizations_url: "https://api.github.com/users/git4rails/orgs",
    repos_url: "https://api.github.com/users/git4rails/repos",
    events_url: "https://api.github.com/users/git4rails/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/git4rails/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mdeiters",
    id: 7330,
    node_id: "MDQ6VXNlcjczMzA=",
    avatar_url: "https://avatars.githubusercontent.com/u/7330?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mdeiters",
    html_url: "https://github.com/mdeiters",
    followers_url: "https://api.github.com/users/mdeiters/followers",
    following_url:
      "https://api.github.com/users/mdeiters/following{/other_user}",
    gists_url: "https://api.github.com/users/mdeiters/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mdeiters/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mdeiters/subscriptions",
    organizations_url: "https://api.github.com/users/mdeiters/orgs",
    repos_url: "https://api.github.com/users/mdeiters/repos",
    events_url: "https://api.github.com/users/mdeiters/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mdeiters/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hobbeswalsh",
    id: 14958,
    node_id: "MDQ6VXNlcjE0OTU4",
    avatar_url: "https://avatars.githubusercontent.com/u/14958?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hobbeswalsh",
    html_url: "https://github.com/hobbeswalsh",
    followers_url: "https://api.github.com/users/hobbeswalsh/followers",
    following_url:
      "https://api.github.com/users/hobbeswalsh/following{/other_user}",
    gists_url: "https://api.github.com/users/hobbeswalsh/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hobbeswalsh/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hobbeswalsh/subscriptions",
    organizations_url: "https://api.github.com/users/hobbeswalsh/orgs",
    repos_url: "https://api.github.com/users/hobbeswalsh/repos",
    events_url: "https://api.github.com/users/hobbeswalsh/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hobbeswalsh/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hamman",
    id: 35853,
    node_id: "MDQ6VXNlcjM1ODUz",
    avatar_url: "https://avatars.githubusercontent.com/u/35853?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hamman",
    html_url: "https://github.com/hamman",
    followers_url: "https://api.github.com/users/hamman/followers",
    following_url: "https://api.github.com/users/hamman/following{/other_user}",
    gists_url: "https://api.github.com/users/hamman/gists{/gist_id}",
    starred_url: "https://api.github.com/users/hamman/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hamman/subscriptions",
    organizations_url: "https://api.github.com/users/hamman/orgs",
    repos_url: "https://api.github.com/users/hamman/repos",
    events_url: "https://api.github.com/users/hamman/events{/privacy}",
    received_events_url: "https://api.github.com/users/hamman/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "sinned",
    id: 56403,
    node_id: "MDQ6VXNlcjU2NDAz",
    avatar_url: "https://avatars.githubusercontent.com/u/56403?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sinned",
    html_url: "https://github.com/sinned",
    followers_url: "https://api.github.com/users/sinned/followers",
    following_url: "https://api.github.com/users/sinned/following{/other_user}",
    gists_url: "https://api.github.com/users/sinned/gists{/gist_id}",
    starred_url: "https://api.github.com/users/sinned/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sinned/subscriptions",
    organizations_url: "https://api.github.com/users/sinned/orgs",
    repos_url: "https://api.github.com/users/sinned/repos",
    events_url: "https://api.github.com/users/sinned/events{/privacy}",
    received_events_url: "https://api.github.com/users/sinned/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "altay",
    id: 82309,
    node_id: "MDQ6VXNlcjgyMzA5",
    avatar_url: "https://avatars.githubusercontent.com/u/82309?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/altay",
    html_url: "https://github.com/altay",
    followers_url: "https://api.github.com/users/altay/followers",
    following_url: "https://api.github.com/users/altay/following{/other_user}",
    gists_url: "https://api.github.com/users/altay/gists{/gist_id}",
    starred_url: "https://api.github.com/users/altay/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/altay/subscriptions",
    organizations_url: "https://api.github.com/users/altay/orgs",
    repos_url: "https://api.github.com/users/altay/repos",
    events_url: "https://api.github.com/users/altay/events{/privacy}",
    received_events_url: "https://api.github.com/users/altay/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ascheink",
    id: 102197,
    node_id: "MDQ6VXNlcjEwMjE5Nw==",
    avatar_url: "https://avatars.githubusercontent.com/u/102197?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ascheink",
    html_url: "https://github.com/ascheink",
    followers_url: "https://api.github.com/users/ascheink/followers",
    following_url:
      "https://api.github.com/users/ascheink/following{/other_user}",
    gists_url: "https://api.github.com/users/ascheink/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ascheink/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ascheink/subscriptions",
    organizations_url: "https://api.github.com/users/ascheink/orgs",
    repos_url: "https://api.github.com/users/ascheink/repos",
    events_url: "https://api.github.com/users/ascheink/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ascheink/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "freq32",
    id: 153156,
    node_id: "MDQ6VXNlcjE1MzE1Ng==",
    avatar_url: "https://avatars.githubusercontent.com/u/153156?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/freq32",
    html_url: "https://github.com/freq32",
    followers_url: "https://api.github.com/users/freq32/followers",
    following_url: "https://api.github.com/users/freq32/following{/other_user}",
    gists_url: "https://api.github.com/users/freq32/gists{/gist_id}",
    starred_url: "https://api.github.com/users/freq32/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/freq32/subscriptions",
    organizations_url: "https://api.github.com/users/freq32/orgs",
    repos_url: "https://api.github.com/users/freq32/repos",
    events_url: "https://api.github.com/users/freq32/events{/privacy}",
    received_events_url: "https://api.github.com/users/freq32/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "tombenner",
    id: 193898,
    node_id: "MDQ6VXNlcjE5Mzg5OA==",
    avatar_url: "https://avatars.githubusercontent.com/u/193898?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/tombenner",
    html_url: "https://github.com/tombenner",
    followers_url: "https://api.github.com/users/tombenner/followers",
    following_url:
      "https://api.github.com/users/tombenner/following{/other_user}",
    gists_url: "https://api.github.com/users/tombenner/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/tombenner/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tombenner/subscriptions",
    organizations_url: "https://api.github.com/users/tombenner/orgs",
    repos_url: "https://api.github.com/users/tombenner/repos",
    events_url: "https://api.github.com/users/tombenner/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/tombenner/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Telofy",
    id: 223663,
    node_id: "MDQ6VXNlcjIyMzY2Mw==",
    avatar_url: "https://avatars.githubusercontent.com/u/223663?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Telofy",
    html_url: "https://github.com/Telofy",
    followers_url: "https://api.github.com/users/Telofy/followers",
    following_url: "https://api.github.com/users/Telofy/following{/other_user}",
    gists_url: "https://api.github.com/users/Telofy/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Telofy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Telofy/subscriptions",
    organizations_url: "https://api.github.com/users/Telofy/orgs",
    repos_url: "https://api.github.com/users/Telofy/repos",
    events_url: "https://api.github.com/users/Telofy/events{/privacy}",
    received_events_url: "https://api.github.com/users/Telofy/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "audunfo",
    id: 316324,
    node_id: "MDQ6VXNlcjMxNjMyNA==",
    avatar_url: "https://avatars.githubusercontent.com/u/316324?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/audunfo",
    html_url: "https://github.com/audunfo",
    followers_url: "https://api.github.com/users/audunfo/followers",
    following_url:
      "https://api.github.com/users/audunfo/following{/other_user}",
    gists_url: "https://api.github.com/users/audunfo/gists{/gist_id}",
    starred_url: "https://api.github.com/users/audunfo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/audunfo/subscriptions",
    organizations_url: "https://api.github.com/users/audunfo/orgs",
    repos_url: "https://api.github.com/users/audunfo/repos",
    events_url: "https://api.github.com/users/audunfo/events{/privacy}",
    received_events_url: "https://api.github.com/users/audunfo/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "colinpollock",
    id: 359160,
    node_id: "MDQ6VXNlcjM1OTE2MA==",
    avatar_url: "https://avatars.githubusercontent.com/u/359160?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/colinpollock",
    html_url: "https://github.com/colinpollock",
    followers_url: "https://api.github.com/users/colinpollock/followers",
    following_url:
      "https://api.github.com/users/colinpollock/following{/other_user}",
    gists_url: "https://api.github.com/users/colinpollock/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/colinpollock/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/colinpollock/subscriptions",
    organizations_url: "https://api.github.com/users/colinpollock/orgs",
    repos_url: "https://api.github.com/users/colinpollock/repos",
    events_url: "https://api.github.com/users/colinpollock/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/colinpollock/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "decause",
    id: 427420,
    node_id: "MDQ6VXNlcjQyNzQyMA==",
    avatar_url: "https://avatars.githubusercontent.com/u/427420?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/decause",
    html_url: "https://github.com/decause",
    followers_url: "https://api.github.com/users/decause/followers",
    following_url:
      "https://api.github.com/users/decause/following{/other_user}",
    gists_url: "https://api.github.com/users/decause/gists{/gist_id}",
    starred_url: "https://api.github.com/users/decause/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/decause/subscriptions",
    organizations_url: "https://api.github.com/users/decause/orgs",
    repos_url: "https://api.github.com/users/decause/repos",
    events_url: "https://api.github.com/users/decause/events{/privacy}",
    received_events_url: "https://api.github.com/users/decause/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "keppelen",
    id: 602111,
    node_id: "MDQ6VXNlcjYwMjExMQ==",
    avatar_url: "https://avatars.githubusercontent.com/u/602111?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/keppelen",
    html_url: "https://github.com/keppelen",
    followers_url: "https://api.github.com/users/keppelen/followers",
    following_url:
      "https://api.github.com/users/keppelen/following{/other_user}",
    gists_url: "https://api.github.com/users/keppelen/gists{/gist_id}",
    starred_url: "https://api.github.com/users/keppelen/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/keppelen/subscriptions",
    organizations_url: "https://api.github.com/users/keppelen/orgs",
    repos_url: "https://api.github.com/users/keppelen/repos",
    events_url: "https://api.github.com/users/keppelen/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/keppelen/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mattkc7",
    id: 618674,
    node_id: "MDQ6VXNlcjYxODY3NA==",
    avatar_url: "https://avatars.githubusercontent.com/u/618674?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mattkc7",
    html_url: "https://github.com/mattkc7",
    followers_url: "https://api.github.com/users/mattkc7/followers",
    following_url:
      "https://api.github.com/users/mattkc7/following{/other_user}",
    gists_url: "https://api.github.com/users/mattkc7/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mattkc7/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mattkc7/subscriptions",
    organizations_url: "https://api.github.com/users/mattkc7/orgs",
    repos_url: "https://api.github.com/users/mattkc7/repos",
    events_url: "https://api.github.com/users/mattkc7/events{/privacy}",
    received_events_url: "https://api.github.com/users/mattkc7/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dumbyme",
    id: 626476,
    node_id: "MDQ6VXNlcjYyNjQ3Ng==",
    avatar_url: "https://avatars.githubusercontent.com/u/626476?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dumbyme",
    html_url: "https://github.com/dumbyme",
    followers_url: "https://api.github.com/users/dumbyme/followers",
    following_url:
      "https://api.github.com/users/dumbyme/following{/other_user}",
    gists_url: "https://api.github.com/users/dumbyme/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dumbyme/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dumbyme/subscriptions",
    organizations_url: "https://api.github.com/users/dumbyme/orgs",
    repos_url: "https://api.github.com/users/dumbyme/repos",
    events_url: "https://api.github.com/users/dumbyme/events{/privacy}",
    received_events_url: "https://api.github.com/users/dumbyme/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "MaxSchultz",
    id: 664787,
    node_id: "MDQ6VXNlcjY2NDc4Nw==",
    avatar_url: "https://avatars.githubusercontent.com/u/664787?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/MaxSchultz",
    html_url: "https://github.com/MaxSchultz",
    followers_url: "https://api.github.com/users/MaxSchultz/followers",
    following_url:
      "https://api.github.com/users/MaxSchultz/following{/other_user}",
    gists_url: "https://api.github.com/users/MaxSchultz/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/MaxSchultz/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/MaxSchultz/subscriptions",
    organizations_url: "https://api.github.com/users/MaxSchultz/orgs",
    repos_url: "https://api.github.com/users/MaxSchultz/repos",
    events_url: "https://api.github.com/users/MaxSchultz/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/MaxSchultz/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "alienintheheights",
    id: 682815,
    node_id: "MDQ6VXNlcjY4MjgxNQ==",
    avatar_url: "https://avatars.githubusercontent.com/u/682815?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/alienintheheights",
    html_url: "https://github.com/alienintheheights",
    followers_url: "https://api.github.com/users/alienintheheights/followers",
    following_url:
      "https://api.github.com/users/alienintheheights/following{/other_user}",
    gists_url: "https://api.github.com/users/alienintheheights/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/alienintheheights/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/alienintheheights/subscriptions",
    organizations_url: "https://api.github.com/users/alienintheheights/orgs",
    repos_url: "https://api.github.com/users/alienintheheights/repos",
    events_url:
      "https://api.github.com/users/alienintheheights/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/alienintheheights/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "wboykinm",
    id: 735463,
    node_id: "MDQ6VXNlcjczNTQ2Mw==",
    avatar_url: "https://avatars.githubusercontent.com/u/735463?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/wboykinm",
    html_url: "https://github.com/wboykinm",
    followers_url: "https://api.github.com/users/wboykinm/followers",
    following_url:
      "https://api.github.com/users/wboykinm/following{/other_user}",
    gists_url: "https://api.github.com/users/wboykinm/gists{/gist_id}",
    starred_url: "https://api.github.com/users/wboykinm/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/wboykinm/subscriptions",
    organizations_url: "https://api.github.com/users/wboykinm/orgs",
    repos_url: "https://api.github.com/users/wboykinm/repos",
    events_url: "https://api.github.com/users/wboykinm/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/wboykinm/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jonbischke",
    id: 755039,
    node_id: "MDQ6VXNlcjc1NTAzOQ==",
    avatar_url: "https://avatars.githubusercontent.com/u/755039?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jonbischke",
    html_url: "https://github.com/jonbischke",
    followers_url: "https://api.github.com/users/jonbischke/followers",
    following_url:
      "https://api.github.com/users/jonbischke/following{/other_user}",
    gists_url: "https://api.github.com/users/jonbischke/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jonbischke/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jonbischke/subscriptions",
    organizations_url: "https://api.github.com/users/jonbischke/orgs",
    repos_url: "https://api.github.com/users/jonbischke/repos",
    events_url: "https://api.github.com/users/jonbischke/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jonbischke/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "vpr",
    id: 931710,
    node_id: "MDQ6VXNlcjkzMTcxMA==",
    avatar_url: "https://avatars.githubusercontent.com/u/931710?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/vpr",
    html_url: "https://github.com/vpr",
    followers_url: "https://api.github.com/users/vpr/followers",
    following_url: "https://api.github.com/users/vpr/following{/other_user}",
    gists_url: "https://api.github.com/users/vpr/gists{/gist_id}",
    starred_url: "https://api.github.com/users/vpr/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/vpr/subscriptions",
    organizations_url: "https://api.github.com/users/vpr/orgs",
    repos_url: "https://api.github.com/users/vpr/repos",
    events_url: "https://api.github.com/users/vpr/events{/privacy}",
    received_events_url: "https://api.github.com/users/vpr/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "UbuntuEvangelist",
    id: 1058663,
    node_id: "MDQ6VXNlcjEwNTg2NjM=",
    avatar_url: "https://avatars.githubusercontent.com/u/1058663?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/UbuntuEvangelist",
    html_url: "https://github.com/UbuntuEvangelist",
    followers_url: "https://api.github.com/users/UbuntuEvangelist/followers",
    following_url:
      "https://api.github.com/users/UbuntuEvangelist/following{/other_user}",
    gists_url: "https://api.github.com/users/UbuntuEvangelist/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/UbuntuEvangelist/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/UbuntuEvangelist/subscriptions",
    organizations_url: "https://api.github.com/users/UbuntuEvangelist/orgs",
    repos_url: "https://api.github.com/users/UbuntuEvangelist/repos",
    events_url:
      "https://api.github.com/users/UbuntuEvangelist/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/UbuntuEvangelist/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "pmontp19",
    id: 1065202,
    node_id: "MDQ6VXNlcjEwNjUyMDI=",
    avatar_url: "https://avatars.githubusercontent.com/u/1065202?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/pmontp19",
    html_url: "https://github.com/pmontp19",
    followers_url: "https://api.github.com/users/pmontp19/followers",
    following_url:
      "https://api.github.com/users/pmontp19/following{/other_user}",
    gists_url: "https://api.github.com/users/pmontp19/gists{/gist_id}",
    starred_url: "https://api.github.com/users/pmontp19/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/pmontp19/subscriptions",
    organizations_url: "https://api.github.com/users/pmontp19/orgs",
    repos_url: "https://api.github.com/users/pmontp19/repos",
    events_url: "https://api.github.com/users/pmontp19/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/pmontp19/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "toxtli",
    id: 1299233,
    node_id: "MDQ6VXNlcjEyOTkyMzM=",
    avatar_url: "https://avatars.githubusercontent.com/u/1299233?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/toxtli",
    html_url: "https://github.com/toxtli",
    followers_url: "https://api.github.com/users/toxtli/followers",
    following_url: "https://api.github.com/users/toxtli/following{/other_user}",
    gists_url: "https://api.github.com/users/toxtli/gists{/gist_id}",
    starred_url: "https://api.github.com/users/toxtli/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/toxtli/subscriptions",
    organizations_url: "https://api.github.com/users/toxtli/orgs",
    repos_url: "https://api.github.com/users/toxtli/repos",
    events_url: "https://api.github.com/users/toxtli/events{/privacy}",
    received_events_url: "https://api.github.com/users/toxtli/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "entelobot",
    id: 1421223,
    node_id: "MDQ6VXNlcjE0MjEyMjM=",
    avatar_url: "https://avatars.githubusercontent.com/u/1421223?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/entelobot",
    html_url: "https://github.com/entelobot",
    followers_url: "https://api.github.com/users/entelobot/followers",
    following_url:
      "https://api.github.com/users/entelobot/following{/other_user}",
    gists_url: "https://api.github.com/users/entelobot/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/entelobot/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/entelobot/subscriptions",
    organizations_url: "https://api.github.com/users/entelobot/orgs",
    repos_url: "https://api.github.com/users/entelobot/repos",
    events_url: "https://api.github.com/users/entelobot/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/entelobot/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "arslnb",
    id: 2177963,
    node_id: "MDQ6VXNlcjIxNzc5NjM=",
    avatar_url: "https://avatars.githubusercontent.com/u/2177963?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/arslnb",
    html_url: "https://github.com/arslnb",
    followers_url: "https://api.github.com/users/arslnb/followers",
    following_url: "https://api.github.com/users/arslnb/following{/other_user}",
    gists_url: "https://api.github.com/users/arslnb/gists{/gist_id}",
    starred_url: "https://api.github.com/users/arslnb/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/arslnb/subscriptions",
    organizations_url: "https://api.github.com/users/arslnb/orgs",
    repos_url: "https://api.github.com/users/arslnb/repos",
    events_url: "https://api.github.com/users/arslnb/events{/privacy}",
    received_events_url: "https://api.github.com/users/arslnb/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ychong",
    id: 2217207,
    node_id: "MDQ6VXNlcjIyMTcyMDc=",
    avatar_url: "https://avatars.githubusercontent.com/u/2217207?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ychong",
    html_url: "https://github.com/ychong",
    followers_url: "https://api.github.com/users/ychong/followers",
    following_url: "https://api.github.com/users/ychong/following{/other_user}",
    gists_url: "https://api.github.com/users/ychong/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ychong/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ychong/subscriptions",
    organizations_url: "https://api.github.com/users/ychong/orgs",
    repos_url: "https://api.github.com/users/ychong/repos",
    events_url: "https://api.github.com/users/ychong/events{/privacy}",
    received_events_url: "https://api.github.com/users/ychong/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "csjaba",
    id: 2398264,
    node_id: "MDQ6VXNlcjIzOTgyNjQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/2398264?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/csjaba",
    html_url: "https://github.com/csjaba",
    followers_url: "https://api.github.com/users/csjaba/followers",
    following_url: "https://api.github.com/users/csjaba/following{/other_user}",
    gists_url: "https://api.github.com/users/csjaba/gists{/gist_id}",
    starred_url: "https://api.github.com/users/csjaba/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/csjaba/subscriptions",
    organizations_url: "https://api.github.com/users/csjaba/orgs",
    repos_url: "https://api.github.com/users/csjaba/repos",
    events_url: "https://api.github.com/users/csjaba/events{/privacy}",
    received_events_url: "https://api.github.com/users/csjaba/received_events",
    type: "User",
    site_admin: false,
  },
];

const mockdata = {
  login: "Meiti-021",
  id: 89641841,
  node_id: "MDQ6VXNlcjg5NjQxODQx",
  avatar_url: "https://avatars.githubusercontent.com/u/89641841?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Meiti-021",
  html_url: "https://github.com/Meiti-021",
  followers_url: "https://api.github.com/users/Meiti-021/followers",
  following_url:
    "https://api.github.com/users/Meiti-021/following{/other_user}",
  gists_url: "https://api.github.com/users/Meiti-021/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Meiti-021/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Meiti-021/subscriptions",
  organizations_url: "https://api.github.com/users/Meiti-021/orgs",
  repos_url: "https://api.github.com/users/Meiti-021/repos",
  events_url: "https://api.github.com/users/Meiti-021/events{/privacy}",
  received_events_url: "https://api.github.com/users/Meiti-021/received_events",
  type: "User",
  site_admin: false,
  name: "Mahdi dehgani",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: true,
  bio: "Front-End web developer",
  twitter_username: null,
  public_repos: 16,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2021-08-27T11:44:17Z",
  updated_at: "2023-01-02T12:30:13Z",
};

export { followersMock, mockdata };
